### ISSUE TITLE
Linebreaks in lists are preserved

### ISSUE THREAD

**Issue by mgmart** [chaseadamsio/goorgeous#50]
I tried to convert the markdown content of our Hugo site to org. Which worked fine. Unfortunately Hugo does preserve the line-breaks in lists.

In the attached image I've marked the occurrences with arrows. The red markers are for the next ticket 😄 .

<img width="461" alt="documentation_-_mobileorg" src="https://user-images.githubusercontent.com/3919652/26984209-c9c0501a-4d3e-11e7-97fe-26991871543b.png">

The expected outcome would be as shown in the next image which is the Hugo markdown rendering.

<img width="458" alt="documentation_-_mobileorg" src="https://user-images.githubusercontent.com/3919652/26984238-f06c50f6-4d3e-11e7-8c9e-7f788364f119.png">

And the source code:

<img width="316" alt="_users_peppe_documents_github_mobileorg_github_io_content_documentation_index_org" src="https://user-images.githubusercontent.com/3919652/26984262-09b67172-4d3f-11e7-92a3-8fb551863fa2.png">

**Comment by wd** [comment]
I also found Hugo will not process '=.git=' as attached image shows.

![image](https://user-images.githubusercontent.com/58177/27812447-a642be0e-60a1-11e7-8b83-ef32001a98b1.png)

**Comment by chaseadamsio** [comment]
@wd the issues you raised has been fixed in #51.

**Comment by wd** [comment]
@chaseadamsio I've seen it, and I add a issue to hugo, https://github.com/gohugoio/hugo/issues/3899, hugo have upgraded the depends, it will release in the next version. Thanks.

**Comment by wd** [comment]
Confirmed, this has been fixed at Hugo HEAD version.

**Comment by chaseadamsio** [comment]
@mgmart, sorry for the long delay 😅but I'm re-writing goorgeous. @wd's issues are still fixed in the rewrite but I want to make sure your issues are addressed. Check the commit (listed above) in this issue and let me know if that's the behavior you're expecting.

**Comment by mgmart** [comment]
@chaseadamsio, from looking at the code I would assume that the issue is addressed.
Looking forward to try the rewritten version.

**Comment by chaseadamsio** [comment]
@mgmart you and me both. I'm really excited for what this re-write will do for org support in Hugo and some other ideas I have.

**Comment by wd** [comment]
@chaseadamsio  May be of ftopic, but according to this commit 
 https://github.com/gohugoio/hugo/commit/b6867bf8068fcaaddf1cb7478f4d52a9c1be1411  I found hugo has changed it's org render tool to https://github.com/niklasfasching/go-org/ .

**Comment by chaseadamsio** [comment]
@wd thanks for the heads up...It's kind of a bummer that I was 2 weeks too late. There's still a lot missing (html + html_attr + the way blocks are handled) so I may at least merge the branch into master so that it's complete.

**Comment by chaseadamsio** [comment]
Since t it looks like @niklasfasching PR'ed a new org parser, I'm closing all the issues here, deprecating and archiving goorgeous.
